version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - microservices_net

  producer:
    build:
      context: ./producer
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

  consumer_one:
    build:
      context: ./consumer_one
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

  consumer_two:
    build:
      context: ./consumer_two
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

  consumer_three:
    build:
      context: ./consumer_three
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

  consumer_four:
    build:
      context: ./consumer_four
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

networks:
  microservices_net:
